{
 "title": "opergroups",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Leaf1 e1-49 throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_in_octets{source=\"leaf1:57400\",interface_name=\"ethernet-1/49\"}[5s])*8",
     "legendFormat": "IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_out_octets{source=\"leaf1:57400\",interface_name=\"ethernet-1/49\"}[5s])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Leaf1 e1-50 throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_in_octets{source=\"leaf1:57400\",interface_name=\"ethernet-1/50\"}[5s])*8",
     "legendFormat": "IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_out_octets{source=\"leaf1:57400\",interface_name=\"ethernet-1/50\"}[5s])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Leaf2 e1-49 throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_in_octets{source=\"leaf2:57400\",interface_name=\"ethernet-1/49\"}[5s])*8",
     "legendFormat": "IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_out_octets{source=\"leaf2:57400\",interface_name=\"ethernet-1/49\"}[5s])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Leaf2 e1-50throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_in_octets{source=\"leaf2:57400\",interface_name=\"ethernet-1/50\"}[5s])*8",
     "legendFormat": "IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_out_octets{source=\"leaf2:57400\",interface_name=\"ethernet-1/50\"}[5s])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Leaf1 e1-1 throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_in_octets{source=\"leaf1:57400\",interface_name=\"ethernet-1/1\"}[5s])*8",
     "legendFormat": "IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_out_octets{source=\"leaf1:57400\",interface_name=\"ethernet-1/1\"}[5s])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Topology",
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 9, "y": 7 },
   "options": {
    "content": "![pic](https://gitlab.com/rdodin/pics/-/wikis/uploads/c93bb6f74c32653f8d11b62db985c927/image.png)"
   }
  },
  {
   "title": "Leaf2 e1-1 throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_srl_if_in_octets{source=\"leaf2:57400\",interface_name=\"ethernet-1/1\"}[5s])*8",
     "legendFormat": "IN"
    },
    {
     "expr": "-rate(gnmic_srl_if_out_octets{source=\"leaf2:57400\",interface_name=\"ethernet-1/1\"}[5s])*8",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "leaf1 oper-states",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "gnmic_srl_if_oper_state{source=\"leaf1:57400\", interface_name=\"ethernet-1/1\"}",
     "legendFormat": "e-1/1"
    },
    {
     "expr": "gnmic_srl_if_oper_state{source=\"leaf1:57400\", interface_name=\"ethernet-1/49\"}",
     "legendFormat": "e-1/49"
    },
    {
     "expr": "gnmic_srl_if_oper_state{source=\"leaf1:57400\", interface_name=\"ethernet-1/50\"}",
     "legendFormat": "e-1/50"
    }
   ]
  }
 ]
}