ARG VARIANT="v1.18"
FROM ghcr.io/hellt/upy:${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
